### ISSUE TITLE
Investigate if the same pipeline is used by multiple repositories

### ISSUE THREAD

**Issue by tatterdemalion** [Adphorus/zenhub-charts#2]
@yigitbey got an error on `./manage.py fetch --initial`:

```
Traceback (most recent call last):
  File "/data/zenhub-charts-venv/lib/python3.6/site-packages/django/db/models/query.py", line 480, in update_or_create
    obj = self.select_for_update().get(**lookup)
  File "/data/zenhub-charts-venv/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
boards.models.DoesNotExist: Pipeline matching query does not exist.
```

**Comment by ringods** [comment]
@tatterdemalion surprise: I'm bumping into this too. We have a single Zenhub board with 25 repositories attached to it.

If you could bootstrap me a bit, I'm willing to provide a PR for this one. How would you solve this one?

**Comment by ringods** [comment]
I submitted PR #9 to have this fixed.

**Comment by tatterdemalion** [comment]
Thanks @ringods
